[package]
name = "krb5-cli-print"
description = "Stderr printers that krb5-kinit and krb5-kadmind install"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]

[lints]
workspace = true
