[package]
name = "krb5-config"
description = "krb5.conf / kdc.conf parsing, env vars, and DNS SRV KDC discovery"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
krb5-types.workspace = true
krb5-log.workspace = true
nix.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
