[package]
name = "krb5-protocol"
description = "Kerberos V5 AS/TGS exchanges over UDP/TCP"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
getrandom.workspace = true
krb5-asn1.workspace = true
krb5-config.workspace = true
krb5-crypto.workspace = true
krb5-log.workspace = true
krb5-types.workspace = true
sha1.workspace = true
thiserror.workspace = true
tracing.workspace = true
zeroize.workspace = true

[dev-dependencies]
krb5-kdc.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
