[libdefaults]
    default_realm = KERBER.TEST
    dns_lookup_realm = false
    dns_lookup_kdc = false
    rdns = false
    ticket_lifetime = 10h
    forwardable = true

[realms]
    KERBER.TEST = {
        kdc = 127.0.0.1
        admin_server = 127.0.0.1
    }

[domain_realm]
    .kerber.test = KERBER.TEST
    kerber.test = KERBER.TEST
