#!/usr/bin/env python3
"""Pair differential-gate.sh status-word cells with tagged unit twins.

A status-word cell is a gate grep of
`"case":"<name>","outcome":"ok","error_code":N,"e_text":"…"`. Each such
case must have `// oracle: differential-gate.sh <case>` on a live
`#[test]` fn. Deleting that fn, or leaving a cell untagged, fails.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

ORACLE_RE = re.compile(
    r"^[ \t]*// oracle: differential-gate.sh ([A-Za-z0-9-]+)[ \t]*$"
)
TEST_FN_RE = re.compile(
    r"#\[test\]\s*(?:#\[[^\]]+\]\s*)*(?://[^\n]*\n\s*)*fn ([A-Za-z0-9_]+)",
    re.M,
)
CELL_RE = re.compile(
    r'"case":"([^"]+)","outcome":"ok","error_code":(\d+),"e_text":"((?:\\.|[^"\\])+)"'
)
CASE_PIN_RE = re.compile(r'"case":"([^"]+)"')
FN_LINE_RE = re.compile(r"^[ \t]*(?:pub(?:\([^)]*\))?\s+)?(?:async\s+)?fn ([A-Za-z0-9_]+)\s*\(")

DOC_HEADER = """# Gate ↔ unit index

Generated by `python3 scripts/lib/gate_unit_index.py --write`. Do not
edit by hand. Each `differential-gate.sh` status-word cell
(`error_code` + `e_text`) must have a tagged unit twin:

```
// oracle: differential-gate.sh <case>
```

`scripts/ci-policy.py` fails when a cell has no tag or a tag names a
test that is gone. Extra tags on diffsend cases that do not pin an
`e_text` are allowed.

| case | code | status | unit |
| --- | ---: | --- | --- |
"""


class GateIndexError(Exception):
    """Fail-red for a missing twin, dangling tag, or stale generated doc."""


def status_word_cells(gate_text: str) -> dict[str, tuple[str, str]]:
    """case → (error_code, e_text). Last pin for a case wins."""
    out: dict[str, tuple[str, str]] = {}
    for m in CELL_RE.finditer(gate_text):
        et = m.group(3).replace("\\'", "'").replace("\\\\", "\\")
        out[m.group(1)] = (m.group(2), et)
    return out


def _test_fns(text: str) -> set[str]:
    return set(TEST_FN_RE.findall(text))


def parse_oracles(root: pathlib.Path) -> list[tuple[str, str, str]]:
    """(case, fn, relpath) for every oracle comment that precedes a fn."""
    crates = root / "crates"
    pairs: list[tuple[str, str, str]] = []
    if not crates.is_dir():
        raise GateIndexError("missing crates/")
    for path in sorted(crates.rglob("*.rs")):
        rel = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()
        i = 0
        while i < len(lines):
            m = ORACLE_RE.match(lines[i])
            if not m:
                i += 1
                continue
            cases = [m.group(1)]
            j = i + 1
            while j < len(lines):
                stripped = lines[j].strip()
                om = ORACLE_RE.match(lines[j])
                if om:
                    cases.append(om.group(1))
                    j += 1
                    continue
                if stripped.startswith("#[") or stripped == "" or stripped.startswith("//"):
                    j += 1
                    continue
                break
            fn = None
            while j < len(lines):
                fm = FN_LINE_RE.match(lines[j])
                if fm:
                    fn = fm.group(1)
                    break
                stripped = lines[j].strip()
                if stripped.startswith("#[") or stripped == "" or stripped.startswith("//"):
                    j += 1
                    continue
                break
            if fn is None:
                raise GateIndexError(f"{rel}:{i + 1}: oracle comment has no following fn")
            for case in cases:
                pairs.append((case, fn, rel))
            i = j if j > i else i + 1
        # dangling later: fn must be a #[test]
    return pairs


def rust_test_fns(root: pathlib.Path) -> set[str]:
    names: set[str] = set()
    crates = root / "crates"
    if not crates.is_dir():
        return names
    for path in crates.rglob("*.rs"):
        names |= _test_fns(path.read_text(encoding="utf-8"))
    return names


def render(
    cells: dict[str, tuple[str, str]],
    pairs: list[tuple[str, str, str]],
) -> str:
    by_case: dict[str, list[tuple[str, str]]] = {c: [] for c in cells}
    for case, fn, rel in pairs:
        by_case.setdefault(case, []).append((fn, rel))
    lines = [DOC_HEADER]
    for case in sorted(cells):
        code, et = cells[case]
        twins = by_case.get(case) or []
        if twins:
            unit = ", ".join(f"`{fn}` (`{rel}`)" for fn, rel in twins)
        else:
            unit = "*(missing)*"
        lines.append(f"| `{case}` | {code} | `{et}` | {unit} |\n")
    n = len(cells)
    tagged = sum(1 for c in cells if by_case.get(c))
    lines.append(f"\nPaired **{tagged}/{n}** status-word cells.\n")
    return "".join(lines)


def verify(
    root: pathlib.Path,
    gate_text: str,
    doc_text: str | None,
    allowed_cases: set[str] | None = None,
) -> str:
    cells = status_word_cells(gate_text)
    if not cells:
        raise GateIndexError("differential-gate.sh has no status-word cells")
    pairs = parse_oracles(root)
    tests = rust_test_fns(root)
    if allowed_cases is None:
        allowed_cases = set(CASE_PIN_RE.findall(gate_text)) | set(cells)
    dangling = [(c, fn, rel) for c, fn, rel in pairs if fn not in tests]
    if dangling:
        shown = ", ".join(f"{fn} ({c} in {rel})" for c, fn, rel in dangling[:8])
        raise GateIndexError(f"oracle tag names a missing #[test] fn: {shown}")
    unknown = sorted({c for c, _, _ in pairs if c not in allowed_cases})
    if unknown:
        raise GateIndexError(f"oracle tag for unknown diffsend case(s): {unknown}")
    tagged = {c for c, _, _ in pairs}
    missing = sorted(set(cells) - tagged)
    if missing:
        raise GateIndexError(
            "gate status-word cell(s) have no tagged unit twin: " + ", ".join(missing)
        )
    generated = render(cells, pairs)
    if doc_text is not None and doc_text != generated:
        raise GateIndexError(
            "docs/gate-unit-index.md is stale; run "
            "python3 scripts/lib/gate_unit_index.py --write"
        )
    return generated


def default_paths(root: pathlib.Path) -> tuple[pathlib.Path, pathlib.Path]:
    return (
        root / "scripts" / "differential-gate.sh",
        root / "docs" / "gate-unit-index.md",
    )


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--root",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parents[2],
    )
    p.add_argument("--write", action="store_true")
    ns = p.parse_args(argv)
    root = ns.root.resolve()
    gate_path, doc_path = default_paths(root)
    if not gate_path.is_file():
        print(f"missing {gate_path}", file=sys.stderr)
        return 1
    gate = gate_path.read_text(encoding="utf-8")
    doc = doc_path.read_text(encoding="utf-8") if doc_path.is_file() else None
    try:
        generated = verify(root, gate, None if ns.write else doc)
    except GateIndexError as e:
        print(f"gate-unit-index: {e}", file=sys.stderr)
        return 1
    if ns.write:
        doc_path.parent.mkdir(parents=True, exist_ok=True)
        doc_path.write_text(generated, encoding="utf-8")
        print(f"wrote {doc_path}")
    else:
        print("gate-unit-index: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
