//! MIT `log_tgs_req` / `log_as_req` status words (`do_as_req.c`,
//! `do_tgs_req.c`, `tgs_policy.c`, `kdc_util.c`). These are the KRB-ERROR
//! `e_text` values; `k5_setmsg` strings stay in `Error::Protocol.detail`.

#![allow(dead_code)]

pub const ADD_TO_TRANSITED_LIST: &str = "ADD_TO_TRANSITED_LIST";
pub const BAD_ENCRYPTION_TYPE: &str = "BAD_ENCRYPTION_TYPE";
pub const BAD_TRANSIT: &str = "BAD_TRANSIT";
pub const BAD_TGS_SERVER_NAME: &str = "BAD TGS SERVER NAME";
pub const CANT_FIND_CLIENT_KEY: &str = "CANT_FIND_CLIENT_KEY";
pub const CLIENT_EXPIRED: &str = "CLIENT EXPIRED";
pub const CLIENT_KEY_EXPIRED: &str = "CLIENT KEY EXPIRED";
pub const CLIENT_LOCKED_OUT: &str = "CLIENT LOCKED OUT";
pub const CLIENT_NOT_FOUND: &str = "CLIENT_NOT_FOUND";
pub const EVIDENCE_TICKET_MISMATCH: &str = "EVIDENCE_TICKET_MISMATCH";
pub const EVIDENCE_TKT_NOT_FORWARDABLE: &str = "EVIDENCE_TKT_NOT_FORWARDABLE";
pub const FINDING_SERVER_KEY: &str = "FINDING_SERVER_KEY";
pub const FIND_FAST: &str = "FIND_FAST";
pub const GET_LOCAL_TGT: &str = "GET_LOCAL_TGT";
pub const HEADER_PAC: &str = "HEADER_PAC";
pub const INVALID_AS_OPTIONS: &str = "INVALID AS OPTIONS";
pub const INVALID_LINEAGE: &str = "INVALID LINEAGE";
pub const INVALID_S4U2PROXY_OPTIONS: &str = "INVALID_S4U2PROXY_OPTIONS";
pub const INVALID_S4U2SELF_CHECKSUM: &str = "INVALID_S4U2SELF_CHECKSUM";
pub const INVALID_S4U2SELF_OPTIONS: &str = "INVALID S4U2SELF OPTIONS";
pub const INVALID_S4U2SELF_REQUEST_SERVER_MISMATCH: &str =
    "INVALID_S4U2SELF_REQUEST_SERVER_MISMATCH";
pub const LOOKING_UP_CLIENT: &str = "LOOKING_UP_CLIENT";
pub const LOOKING_UP_SERVER: &str = "LOOKING_UP_SERVER";
pub const NEEDED_PREAUTH: &str = "NEEDED_PREAUTH";
pub const NO_2ND_TKT: &str = "NO_2ND_TKT";
pub const NO_HW_PREAUTH: &str = "NO HW PREAUTH";
pub const NON_POSTDATABLE_TICKET: &str = "NON-POSTDATABLE TICKET";
pub const NOT_ALLOWED_TO_DELEGATE: &str = "NOT_ALLOWED_TO_DELEGATE";
pub const NOT_CROSS_REALM_REQUEST: &str = "NOT_CROSS_REALM_REQUEST";
pub const NOT_YET_VALID: &str = "NOT_YET_VALID";
pub const NULL_CLIENT: &str = "NULL_CLIENT";
pub const NULL_SERVER: &str = "NULL_SERVER";
pub const POSTDATE_NOT_ALLOWED: &str = "POSTDATE NOT ALLOWED";
pub const PREAUTH_FAILED: &str = "PREAUTH_FAILED";
pub const PROCESS_TGS: &str = "PROCESS_TGS";
pub const READ_COOKIE: &str = "READ_COOKIE";
pub const RENEW_SERVER_MISMATCH: &str = "SERVER DIDN'T MATCH TICKET FOR RENEW/FORWARD/ETC";
pub const REQUIRED_PWCHANGE: &str = "REQUIRED PWCHANGE";
pub const S4U2PROXY_NO_STKT_PAC: &str = "S4U2PROXY_NO_STKT_PAC";
pub const S4U2SELF_CLIENT_NOT_OURS: &str = "S4U2SELF_CLIENT_NOT_OURS";
pub const SECOND_TKT_PAC: &str = "2ND_TKT_PAC";
pub const SECOND_TKT_SERVER: &str = "2ND_TKT_SERVER";
pub const SERVER_LOCKED_OUT: &str = "SERVER LOCKED OUT";
pub const SERVER_NOT_ALLOWED: &str = "SERVER NOT ALLOWED";
pub const SERVER_NOT_FOUND: &str = "SERVER_NOT_FOUND";
pub const SERVICE_EXPIRED: &str = "SERVICE EXPIRED";
pub const SERVICE_LOCKED_OUT: &str = "SERVICE LOCKED OUT";
pub const SERVICE_NOT_ALLOWED: &str = "SERVICE NOT ALLOWED";
pub const TGT_BASED_NOT_ALLOWED: &str = "TGT BASED NOT ALLOWED";
pub const TICKET_NOT_RENEWABLE: &str = "TICKET NOT RENEWABLE";
pub const TICKET_NOT_VALID: &str = "TICKET NOT VALID";
pub const TKT_EXPIRED: &str = "TKT_EXPIRED";
pub const UNKNOWN_REASON: &str = "UNKNOWN_REASON";
pub const UNKNOWN_S4U2SELF_PRINCIPAL: &str = "UNKNOWN_S4U2SELF_PRINCIPAL";
pub const UNSUPPORTED_S4U2PROXY_REQUEST: &str = "UNSUPPORTED_S4U2PROXY_REQUEST";
pub const VALIDATE_TRANSIT_TYPE: &str = "VALIDATE_TRANSIT_TYPE";
pub const VALIDATE_VALID_TICKET: &str = "VALIDATE VALID TICKET";
